topics:
  - title: Зарядка и батарея
    slug: charging
    topicId: 11517
    pinned: data/pinned/charging.md
    botPinnedId: 1413222
  - title: Автозвук
    slug: audio
    topicId: 578617
    pinned: data/pinned/audio.md
    botPinnedId: 1413090
  - title: Выбор и покупка | Сравнение
    slug: choice
    topicId: 8973
    pinned: data/pinned/choice.md
    botPinnedId: 1413079
  - title: Постановка на учёт
    slug: registration
    topicId: 8977
    botPinnedId: 1413056
    pinned: data/pinned/registration.md
  - title: Voyah Courage
    slug: courage
    topicId: 601095
    pinned: data/pinned/courage.md
    botPinnedId: 1413239
  - title: Прошивка | SIM
    slug: firmware
    topicId: 11800
    pinned: data/pinned/firmware.md
